travelbook:
  datasource:
    jdbc-url: "jdbc:mysql://localhost:3306/travelbook"
    #jdbc-url: "jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: root
    password: 1234
    ddl: update
    show-sql: false
    create-scheme-ddl-script: false
  
  # Default definition
  default:
    currency: JPY
  
  datafixture: false
    
  security:
    # RSA key pair for generating JSON Web Token(JWT)
    jwt:
      private-key-path: "C:/temp/private.key"
      public-key-path: "C:/temp/public.key"
     